# The URL the site will be built for
base_url = "https://wcchin.github.io/"
title = "Benny Chin's Page"
default_language = "en"

theme = "pico2"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
      { name = "tags", paginate_by = 10, feed = true },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[search]
index_format = "elasticlunr_json"

[extra]
# Put all your custom variables here
index_page = "home"
top_menu = ["home","publication","experience","project","teaching","links"]
copyright_string = "By [Benny Chin](https://wcchin.github.io/) – %YEAR% for fun."
author = "CHIN Wei Chien Benny 陳威全"
avatar_src = "images/benny_line.png"
logo_src = "images/logo.webp"
nonce=""
description = "My academic portfolio page"


[extra.giscus]
data_repo="wcchin/wcchin.github.io"
data_repo_id="R_kgDOLQ4cpw"
data_category="General"
data_category_id="DIC_kwDOLQ4cp84CdIjK"
data_mapping="url"
data_strict="0"
data_reactions_enabled="0"
data_emit_metadata="0"
data_input_position="bottom"
data_lang="en"
crossorigin="anonymous"
src="https://giscus.app/client.js"


[extra.footer.icons]
github = "https://github.com/wcchin"
linkedin = "https://www.linkedin.com/in/wcchin/"
researchgate = "https://www.researchgate.net/profile/Benny_Chin"
gscholar = "https://scholar.google.com/citations?user=P2IJvyQAAAAJ"
orcid = "https://orcid.org/0000-0001-7215-3303"
ieee = "https://ieeexplore.ieee.org/author/37088386058"
pubmed = "https://www.ncbi.nlm.nih.gov/myncbi/wei%20chien%20benny.chin.1/bibliography/public/"
semanticscholar = "https://www.semanticscholar.org/author/W.-Chin/40429039"
ssrn = "https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=4909051"
clarivate = "https://www.webofscience.com/wos/author/record/AAH-2292-2019"
dblp = "https://dblp.org/pid/147/9316.html"
scopus = "https://www.scopus.com/authid/detail.uri?authorId=56596201400"
osf = "https://osf.io/user/rqju5"
